  
language: java

jdk:
  - openjdk8

branches:
  only:
  - master
  - development

before_script: 
  - cd seip2020_practical_assignments  # enter Maven root directory

script: 
  - mvn clean package 

after_success:
- echo "Hello there!"
